### ISSUE TITLE
Renderflex Overflow

### ISSUE THREAD

**Issue by chinyavadav** [david-legend/onboarding-app#1]
![image](https://user-images.githubusercontent.com/16150355/80898476-20ecd900-8d04-11ea-8acd-8c3a5f8ad76b.png)
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 2.2 pixels on the bottom.

The relevant error-causing widget was: 
  Column file:///Users/chinyavadav/Documents/Bayah/bayah/lib/screens/registration_screen.dart:115:18
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

**Comment by david-legend** [comment]
thanks will look at it and fix it?
Have you come up with a solution yet ??

**Comment by chinyavadav** [comment]
So far I changed margin from MARGIN_20 to MARGIN_18

 child: Card(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(Sizes.RADIUS_8),
        ),
        child: Container(
          margin: const EdgeInsets.symmetric(
            horizontal: Sizes.MARGIN_18,
            vertical: Sizes.MARGIN_18,
          ),

**Comment by david-legend** [comment]
I think we should increase the height of the card.

Container(
                height: heightOfScreen * 0.55,
                child: _buildRegistration(),
              ),
              Container(
                height: heightOfScreen * 0.35,
                child: _buildCodeCard(),
              ),
              SizedBox(height: heightOfScreen * 0.1),
