### ISSUE TITLE
Include a LICENSE

### ISSUE THREAD

**Issue by KipCrossing** [david-legend/onboarding-app#2]
Hey,

Would you consider adding an open-source LICENSE to this project?

Thanks

**Comment by david-legend** [comment]
okay will do that ASAP

**Comment by KipCrossing** [comment]
Awesome! And great work on all your flutter projects.

**Comment by KipCrossing** [comment]
I have noticed a lot of flutter projects tend to go for the BSD license - same as the official flutter repo.

**Comment by david-legend** [comment]
Okay, Thanks very much

**Comment by david-legend** [comment]
I have added it.. will go ahead and add it to all my open-source projects then

**Comment by KipCrossing** [comment]
Don't put BSD on all your projects. The flutter ones are probably fine, but if you want to protect your work or yourself, there are different licences for different applications. I'd be happy to discuss this with you if you would like guidence with licencing. I'll shoot you an email and say hi

**Comment by david-legend** [comment]
Coool I would like that
